/* this code demonstrate that
 * it is imposible to catch more than one exception in destructors
*/

#include "TestSynchronize.h"
#include "TestAssocSearch.h"

int main()
{
//    testSynchronize();
    testAssocSearch();
}
